api/urls.py
from django.urls import path
from api.views import *

app_name = 'api'

urlpatterns = [
    path('projectlist', ProjectListAPIView.as_view({'get':'list'}), name="api_projectlist"),
]

itmrprojectmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('api/', include('api.urls')),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import *

app_name = 'mainapp'

urlpatterns = [
    path('endpages/<str:status>', redirectPageView.as_view()),    
    path('login', signin, name="signin"),
    path('signout', signout, name="signout"),
    path('dashboard', projectlistView.as_view(), name="projectlist"),
    path('delete/<pk>', deleteEntry.as_view(), name="deleteentry"),
    path('userlist', allUserList.as_view(), name="userlist"),
    path('user/resetpassword/', changePassword.as_view(), name="changePassword"),
]

templates/allusers.html
{% extends 'base.html' %}     
{% block body %}
    <div class="container col-xl-6 col-xxl-6 px-4 py-5">
      <div class="row align-items-center g-5 py-5">
        <form class="p-5 border rounded-3 bg-light" action="{% url 'mainapp:changePassword' %}" method="POST">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <!-- <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label> -->
            <!-- <label for="users">Select User Email</label> -->

            <select name="users" id="users" class="form-control" required>
              <option value="">Select Username</option>
              {% for user in allusers %}
              <option value="{{user.id}}">{{user.username}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingPassword" name="floatingPassword" placeholder="Password" required>
            <label for="floatingPassword">New Password</label>
          </div>
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingConfirmPassword" name="floatingConfirmPassword" placeholder="Password" required>
            <label for="floatingPassword">Confirm Password</label>
          </div>
          
          <button class="w-100 btn btn-lg btn-primary" type="submit">Change Password</button>
        </form>
      
    {% endblock %}
    {% block javascript %}
    
    <script>
      $(document).ready(function() {
        $("button[type='submit']").prop('disabled', true);
        $(":text").keyup(function(){
          if($("#floatingPassword").val().trim()!='' && $("#floatingPassword").val().trim() == $("#floatingConfirmPassword").val().trim()){
            $("button[type='submit']").prop('disabled', false);
          }
        })
      })
    </script>
    {% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Project List</title>


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/static/images/favicon_io/site.webmanifest">
    <script src="https://kit.fontawesome.com/fa68abc7e7.js" crossorigin="anonymous"></script>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }
        
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <!-- datapicker CSS
		============================================ -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!-- Custom styles for this template -->
    <link href="/static/css/navbar-top-fixed.css" rel="stylesheet">
</head>

<body>
    <header class="d-flex flex-column flex-md-row align-items-center border-bottom">
        <a href="https://itmrresearch.com/" target="_blank" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="/static/images/logo_1.png">
        </a>

        <nav class="d-inline-flex mt-3 mt-md-0 ms-md-auto">
            <a class="nav-item{{dashboard}}" href="{% url 'mainapp:projectlist' %}"><i class="fas fa-home fa-2x"></i><BR>Dashboard</a> {% if user_dep == '1' %}<a class="nav-item{{userlist}}" href="{% url 'mainapp:userlist' %}"><i class="fas fa-user fa-2x"></i><BR>Users</a>
            <a class="nav-item" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fas fa-globe fa-2x"></i><BR>Redirects</a>{% endif %}
            <a class="nav-item" href="{% url 'mainapp:signout' %}"><i class="fas fa-sign-out-alt fa-2x"></i><BR>Signout</a>
        </nav>
    </header>

    

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Redirect Links</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="productionurl">
                  <p>COMPLETE URL: https://www.itmr.co.in/endpages/Complete?PID=&#60;project_id&#62;&UID=XXXXX</p>
                  <p>QUOTAFULL URL: https://www.itmr.co.in/endpages/Quotafull?PID=&#60;project_id&#62;&UID=XXXXX</p>
                  <p>TERMINATE URL: https://www.itmr.co.in/endpages/Terminate?PID=&#60;project_id&#62;&UID=XXXXX</p>
                </div>
                <div class="modal-body" id="localurl">
                    <p>COMPLETE URL: http://127.0.0.1:8000/endpages/Complete?PID=&#60;project_id&#62;&UID=XXXXX</p>
                    <p>QUOTAFULL URL: http://127.0.0.1:8000/endpages/Quotafull?PID=&#60;project_id&#62;&UID=XXXXX</p>
                    <p>TERMINATE URL: http://127.0.0.1:8000/endpages/Terminate?PID=&#60;project_id&#62;&UID=XXXXX</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary cancelBtn" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% block body %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <!-- datapicker JS
		============================================ -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    {% block javascript %} {% endblock %}
    <script>
      function loadredirecturl(){
       if ((window.location.hostname) == '127.0.0.1' ){
          document.getElementById('productionurl').style.display = 'none';
          document.getElementById('localurl').style.display = 'block';
       }
       else{
          document.getElementById('productionurl').style.display = 'block';
          document.getElementById('localurl').style.display = 'none';
       }
      }
      loadredirecturl();
    </script>
</body>

</html>

templates/confirm_delete.html
{% extends 'base.html' %}     
{% block body %}
<div class="container">
    <form method="post" class="row g-3">{% csrf_token %}
        <p style="font-size: 40px; color:rgb(0, 0, 0); font-weight: 600;">Are you sure you want to delete "{{ object }}"?</p>
        <div class="col-md-2">
            <button class="btn btn-danger" type="submit"> <i class="fas fa-check fa-3x"></i></button>
            
        </div>
        <div class="col-md-2">
            <a href="{% url 'mainapp:projectlist' %}"><button class="btn btn-info" type="button"> <i class="fas fa-times fa-3x"></i></button></a>

        </div>
        
    </form>
    
</div>
{% endblock %} 

templates/datatable.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>ITMR Company - Project List</title> 

    <!-- Bootstrap core CSS -->
	  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/static/images/favicon_io/site.webmanifest">
    <meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="/static/css/stylesheet.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  
  <header class="mb-auto">
    <div>
      <img src='/static/images/logo_1.png'>
      
    </div>
  </header>


</div>


    
  </body>
</html>

templates/index.html
{% extends 'base.html' %}     
{% block body %}
    <div class="container">
      <div class="row">
        
        <div class="col-md-2 text-center">
          <label for="status">Status</label>
          <select name="status" id="status" class="status form-control">
            <option value="">Select Status</option>
            <option value="Complete">Complete</option>
            <option value="Terminate">Terminate</option>
            <option value="Quotafull">Quotafull</option>  
          </select>
        </div>
        <div class="col-lg-3 col-md-2 col-sm-2 col-xs-12 text-center">
          <label for="select_date">Date</label>

          <input type="text" class="form-control" name="select_date" id="select_date" placeholder="dd/mm/yyyy - dd/mm/yyyy">
        </div>
        <!-- Button trigger modal -->
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 text-center">
          <label for="project_id">Project ID</label>
          <input type="text" class="form-control" name="project_id" id="project_id" placeholder="Project ID">
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 text-center">
          <label for="unique_id">Unique ID</label>
          <input type="text" class="form-control" name="unique_id" id="unique_id" placeholder="Unique ID">
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12 text-center">
          <label for="ip_address">IP Address</label>
          <input type="text" class="form-control" name="ip_address" id="ip_address" placeholder="IP Address">
        </div>

        

        
    </div>
      <div class="projectlist_table">
        
        <table id="projectlist" class="display" style="width:100%;" >
          <thead>
              <tr>
                  <th>Serial#</th>
                  <th>Unique ID</th>
                  <th>Project ID</th>                  
                  <th>IP Address</th>
                  <!-- <th>Country</th> -->
                  <th>Date</th>
                  <th>Time</th>
                  <th>Status</th>
                  {% if user_dep == '1' %}<th>Action</th>{% endif %}
              </tr>
          </thead>
          
          <!-- <tfoot>
              <tr>
                  <th>Serial No.</th>
                  <th>Status</th>
                  <th>Project ID</th>
                  <th>Unique ID</th>
                  <th>IP Address</th>
                  <th>Date</th>
                  <th>Time</th>
              </tr>
          </tfoot> -->
        </table>
      </div>
    </div>
    {% endblock %}


    
    {% block javascript %}
    
    <script>
      $(document).ready(function() {
        table = $('#projectlist').DataTable( {
            "ajax": {
                "url": "{% url 'api:api_projectlist' %}",
                "dataSrc": ""
            },
            {% if user_dep == '1' %}
            "columnDefs": [ {
              "targets": -1,
              "data": null,
              "defaultContent": "<button type='button' class='btn-danger' id='deletebutton'>Delete Row</button>"
            } ],{% endif %}
            "columns": [
              { "data": "id" },
              { "data": "unique_id" },
              { "data": "project_id" },
              { "data": "ip_address" },
              // { "data": "country" },
              { "data": "created_date" },
              { "data": "created_time" },
              { "data": "status" },
              {% if user_dep == '1' %}{ "data": null }{% endif %}

            ],
            "order": [[ 0, "desc" ]],
            "lengthMenu": [[1000, -1], [1000, "All"]]
        } );

        table.columns(6).every( function() {
          var that = this;
          $('#status').on('change', function() {
              if (that.search() !== this.value) {
                  that.search(this.value).draw();
              }
          });
        });

        table.columns(2).every( function() {
          var that = this;
          $('#project_id').on('keyup', function() {
              if (that.search() !== this.value) {
                  that.search(this.value).draw();
              }
          });
        });

        table.columns(1).every( function() {
          var that = this;
          $('#unique_id').on('keyup', function() {
              if (that.search() !== this.value) {
                  that.search(this.value).draw();
              }
          });
        });

        table.columns(3).every( function() {
          var that = this;
          $('#ip_address').on('keyup', function() {
              if (that.search() !== this.value) {
                  that.search(this.value).draw();
              }
          });
        });
        {% if user_dep == '1' %}
        $('#projectlist tbody').on( 'click', 'button', function () {
          var data = table.row( $(this).parents('tr') ).data();
          // window.location.assign("http://127.0.0.1:8000/delete/" + data.id)        
          window.location.assign("https://www.itmr.co.in/delete/" + data.id)        
        });
        {% endif %}

      });
    </script>
    <script>
      
      $(function() {
        $('input[name="select_date"]').daterangepicker({
          opens: 'left',
          locale: {
            format: 'YYYY-MM-DD'
          },
        }, function(start, end, label) {
          var table = $('#projectlist').DataTable();
          
            $.fn.dataTableExt.afnFiltering.push(
              function( oSettings, aData, iDataIndex ) {
                console.log("Inside Function called")
                var iFini = $("input[name='select_date']").data('daterangepicker').startDate.format("YYYY-MM-DD");
                var iFfin = $("input[name='select_date']").data('daterangepicker').endDate.format("YYYY-MM-DD");
                
                var iStartDateCol = 4;
                var iEndDateCol = 4;
                iFini=iFini.substring(0,4) + iFini.substring(5,7)+ iFini.substring(8,10);
                iFfin=iFfin.substring(0,4) + iFfin.substring(5,7)+ iFfin.substring(8,10);
                var datofini=aData[iStartDateCol].substring(0,4) + aData[iStartDateCol].substring(5,7)+ aData[iStartDateCol].substring(8,10);
                var datoffin=aData[iEndDateCol].substring(0,4) + aData[iEndDateCol].substring(5,7)+ aData[iEndDateCol].substring(8,10);
             
                if ( iFini === "" && iFfin === "" )
                {
                  return true;
                }
                else if ( iFini <= datofini && iFfin === "")
                {
                  return true;
                }
                else if ( iFfin >= datoffin && iFini === "")
                {
                  return true;
                }
                else if (iFini <= datofini && iFfin >= datoffin)
                {
                  return true;
                }
                return false;
              }
            );

            table.draw();
        });
      });
    </script>
    {% endblock %}
    

templates/landingpage.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>ITMR Company</title> 

    <!-- Bootstrap core CSS -->
	  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="/static/images/favicon_io/site.webmanifest">
    <meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="/static/css/stylesheet.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <div class="text-center">
        <a href="https://itmrresearch.com/">
        <img src='/static/images/logo_1.png' class="rounded float-start">
      </a>
      </div>
      

      <main class="px-3">
        <h1>{{redirectpageheading}}</h1>
        <p class="lead">{{redirectpagemessage}}</p>
        
      </main>
      {% if not reentry %}
      <div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">UID</th>
              <th scope="col">PID</th>
              <th scope="col">Status</th>
              <th scope="col">Ip_Address</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">{{UID}}</th>
              <td>{{PID}}</td>
              <td>{{status}}</td>
              <td>{{ip_address}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      {% endif %}

      
    </div>    
  </body>
</html>

templates/signin.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>Sign In | ITMR</title>
  <style>
    body{
        /* background-image: radial-gradient(ellipse farthest-corner at 0 140%, #5e56cf 10%,#FFF 70%, #5186e9 70%); */
        background-image: url('/static/images/login.jpg');
        background-size: cover;
        color: rgb(255 255 255);
        font-weight: 500;
        /* width: 200px; */
        height: 610px;
        border-radius: 10px;
        margin-top: 50px;
        display: block;
        /* background-image: url("paper.gif"); */
        /* box-shadow: 10px 10px 8px #e91212; */
        /* text-align: center; */
        line-height: 50px;
    }
  </style>
</head>

<body>
  <div class="container col-xl-6 col-xxl-6 px-4 py-5">
    <div class="row justify-content-center align-items-center">
      <div class="text-center">
        <h1>Sign In</h1>
        {% if error %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Opps!!!</strong> {{ error }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endif %}

      </div>
      
    </div>
    <div class="row align-items-center g-5 py-5">
      <!-- <div class="col-md-5"></div> -->
      <form class="p-5 border rounded-3 bg-light" action="" method="POST">
          {% csrf_token %}          
          <div class="form-group">
              <label for="inputEmail4" class="form-label text-dark">Email</label>
              <input type="text" class="form-control" id="inputEmail4" name="email" placeholder="Email">
          </div>
          <div class="form-group">
              <label for="inputPassword4" class="form-label text-dark">Password</label>
              <input type="password" class="form-control" id="inputPassword4" name="password" placeholder="Password">
          </div>
          <div class="form-group">
            <div class="row mt-3">
              <div class="col-4">
                <button type="submit" class="btn btn-dark">Sign In</button>
              </div>
            </div>
          </div>
          
      </form>

    </div>
    
</div>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
</body>

</html>